spring.application.name=calendar-app
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/calendar_app}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:calendar_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:calendar_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=${SPRING_THYMELEAF_CACHE:false}
server.port=${SERVER_PORT:8080}
server.forward-headers-strategy=framework